# Generated by Django 5.0.6 on 2026-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_trailer_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
